//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuGiOh01
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaTipoCarta
    {
        public int IdCartaTipoCarta { get; set; }
        public int IdCarta { get; set; }
        public int IdTipoCarta { get; set; }
        public Nullable<int> IdMagia { get; set; }
        public Nullable<int> IdArmadilha { get; set; }
        public Nullable<int> IdMonstro { get; set; }
        public Nullable<int> IdMonstroEfeito { get; set; }
        public Nullable<int> IdMonstroPendulo { get; set; }
    
        public virtual Armadilha Armadilha { get; set; }
        public virtual Carta Carta { get; set; }
        public virtual Magia Magia { get; set; }
        public virtual Monstro Monstro { get; set; }
        public virtual TipoMonstroEfeito TipoMonstroEfeito { get; set; }
        public virtual MonstroPendulo MonstroPendulo { get; set; }
        public virtual TipoCarta TipoCarta { get; set; }
    }
}
